coverage:
  status:
    project:
      project:
      default:
        # Fail the status if coverage drops by >= 10%
        threshold: 50
    patch:
      default:
        threshold: 50
ignore: 
  - "test"