name: ARM build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install cross compiler
        run: mkdir build; ../install-cc.sh
      - name: CMake
        run: cmake .. -PEDANTIC=ON -RELEASE=ON -DCOVERAGE=OFF -DCROSS=ON
      - name: Build
        run: make -j8