name: C/C++ CI

on:
   [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: cmake -S . -B build
    - name: Build all
      run: cmake --build build -j2
    - name: Run tests
      run: ./build/test/hyped_test
    - name: Install LCOV
      run: | 
        cd ..
        git clone https://github.com/linux-test-project/lcov.git
        cd lcov
        sudo make install
    - name: Get Coverage
      run: make coverage
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./test/coverage/covdata/hyped.covdata # optional
        name: Codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true # optional (default = false)
    
