name: C/C++ CI

on:
   [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache LLVM
      id: cache-llvm
      uses: actions/cache@v2
      with:
        path: ./llvm
        key: llvm-11.0
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11.0"
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}
    - name: Install LCOV
      run: | 
        cd ..
        git clone https://github.com/linux-test-project/lcov.git
        cd lcov
        sudo make install
    - name: CMake
      run: |
        ls $LLVM_PATH/bin
        rm -rf $LLVM_PATH/bin/clang++
        cmake -S . -B build
    - name: Build binaries, run tests and generate coverage
      run: | 
        cmake --build build --target llvm-cov
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/test/coverage/hyped_test.covdata # optional
        name: Codecov-umbrella # optional
        fail_ci_if_error: false
        verbose: true # optional (default = false)
    