name: C/C++ CI

on:
   [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: CMake
      run: cmake -S . -B build
    - name: Build executable and test binary
      run: cmake --build build --target hyped_test -j10
    - name: Install LLVM
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: "11.0"
    - name: Run tests and generate coverage
      run: | 
        rm -rf $LLVM_PATH/bin/clang++
        cmake --build build --target llvm-cov
    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: ./build/test/coverage/hyped.covdata # optional
        name: Codecov-umbrella # optional
        fail_ci_if_error: false
        verbose: true # optional (default = false)
    
