name: x86-64 build, test & coverage

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: cmake -S . -B build -DPEDANTIC=ON -DRELEASE=ON -DCOVERAGE=ON -DCROSS=OFF -DCMAKE_CXX_COMPILER=$(which clang++)
      - name: Build libs
        run: cd build; make eigen rapidjson googletest -j
      - name: Build hyped
        run: cd build; make -j
      - name: Build debugger
        run: cd build; make debugger -j
      - name: Build testrunner
        run: cd build; make testrunner -j
      - name: Cache LLVM and Clang
        id: cache-llvm
        uses: actions/cache@v2
        with:
          path: ./llvm
          key: llvm-11.0
      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: "11.0"
          cached: ${{ steps.cache-llvm.outputs.cache-hit }}
      - name: Install LCOV
        run: |
          cd ..
          git clone https://github.com/linux-test-project/lcov.git
          cd lcov
          sudo make install
      - name: Run tests and generate coverage
        run: |
          rm -rf $LLVM_PATH/bin/clang++
          cd build
          make coverage -j8
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./build/test/coverage/hyped.covdata # optional
          name: Codecov-umbrella # optional
          fail_ci_if_error: false
          verbose: true # optional (default = false)
