name: x86-64 GCC build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: CMake
        run: cmake -S . -B build -DPEDANTIC=ON -DRELEASE=ON -DCOVERAGE=ON -DCROSS=OFF -DCMAKE_CXX_COMPILER=$(which g++)
      - name: Build libs
        run: cd build; make eigen rapidjson googletest -j
      - name: Build hyped
        run: cd build; make -j
      - name: Build debugger
        run: cd build; make debugger -j
      - name: Build testrunner
        run: cd build; make testrunner -j

